SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `board` (
  `id` int(32) NOT NULL,
  `name` varchar(50) NOT NULL,
  `type` int(1) NOT NULL DEFAULT 0 COMMENT '0 - Обычный\r\n1 - файлы\r\n2 - Флеш'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `posts` (
  `id` int(32) NOT NULL,
  `type` int(1) NOT NULL DEFAULT 0,
  `text` varchar(1000) NOT NULL,
  `thread` int(32) NOT NULL DEFAULT 0,
  `board` int(32) NOT NULL DEFAULT 0,
  `name` varchar(50) DEFAULT NULL,
  `ip` varchar(16) NOT NULL,
  `date` int(32) NOT NULL,
  `img` varchar(64) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


ALTER TABLE `board`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `board`
  MODIFY `id` int(32) NOT NULL AUTO_INCREMENT;

ALTER TABLE `posts`
  MODIFY `id` int(32) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
